name: Deploy to forge app to atlassian cloud site staging environment on push

on:
  push:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the source code for deployment
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            static/admin-page/package-lock.json
            static/jsm-portal/package-lock.json
      - run: npm ci
      - run: npm install -g @forge/cli@latest --no-optional
      - name: Build admin page
        run: |
          cd static/admin-page
          npm install
          npm run build
          pwd
          ls -a 
      - name: Build jsm portal page
        run: |
          cd static/jsm-portal
          npm install
          npm run build
          pwd
          ls -a 
      - name: Deploy to atlassian cloud site
        run: |
          branch=${{ github.ref }}
          if [ $branch == "refs/heads/main" ]
          then
            forge deploy -e staging
            forge install --upgrade --non-interactive --site abrega.atlassian.net -e staging -p jira
          elif [ $branch == "refs/heads/production" ]
          then
            forge deploy -e production
          fi
        env:
          FORGE_EMAIL: ${{ secrets.FORGE_EMAIL }}
          FORGE_API_TOKEN: ${{ secrets.FORGE_TOKEN }}
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
